[tool.black]
line-length = 120

[tool.poetry]
name = "raptor"
version = "0.1.0"
description = ""
authors = ["oskar-duda <o.duda@poczta.onet.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
